arangodb/rta-makedata

PULL_REQUEST_TEMPLATE.md
README.md

- https://github.com/arangodb/arangodb/pull/18563
- https://github.com/arangodb/release-test-automation/pull/345

add documentation, pr-template

---

test_data/checkdata.js
test_data/makedata_suites/402_views.js
test_data/makedata_suites/404_views.js

https://arangodb.atlassian.net/browse/QA-396
https://arangodb.atlassian.net/browse/QA-394

QA-394 and QA-396

---

test_data/makedata_suites/051_database_extended_names.js
test_data/makedata_suites/402_views.js

Now we will take into account the fact, that primaryKeyCache and primarySortCache have bugs: https://arangodb.atlassian.net/browse/SEARCH-466

Fix cache support for some versions

---

test_data/makedata_suites/005_check_system_collection.js

added pregel system collection upgrade test

added pregel system collection upgrade test

---

test_data/makedata_suites/005_check_system_collection.js

make mitigation to run _pregel_queries only in new version and other minor fixes

---

test_data/checkdata.js
test_data/cleardata.js
test_data/common.js
test_data/makedata.js
test_data/makedata_suites/000_dummy.js
test_data/makedata_suites/005_check_system_collection.js
test_data/makedata_suites/010_disabled_uuid_check.js
test_data/makedata_suites/020_foxx.js
test_data/makedata_suites/050_database.js
test_data/makedata_suites/051_database_extended_names.js
test_data/makedata_suites/100_collections.js
test_data/makedata_suites/400_views.js
test_data/makedata_suites/401_views.js
test_data/makedata_suites/402_views.js
test_data/makedata_suites/404_views.js
test_data/makedata_suites/500_community_graph.js
test_data/makedata_suites/550_smart_graph.js
test_data/makedata_suites/570_enterprise_graph.js
test_data/makedata_suites/900_oneshard.js

Improve output to be harmonized and have consistent look & feel across all suites. 
- Make printing of delta-Ts optional. 
- enforce gauge-name in progress
- add current file numbers to all outputs

QA-435: cleanup output

---

test_data/cleardata.js
test_data/makedata_suites/500_community_graph.js
test_data/makedata_suites/550_smart_graph.js
test_data/makedata_suites/570_enterprise_graph.js

bug fix: fix "progress" function calls

---

test_data/common.js
test_data/makedata_suites/021_foxx_utf-8.js
test_data/makedata_suites/100_collections.js
test_data/makedata_suites/400_views.js
test_data/makedata_suites/401_views.js
test_data/makedata_suites/402_views.js
test_data/makedata_suites/403_utf8-name-views.js
test_data/makedata_suites/500_community_graph.js
test_data/makedata_suites/550_smart_graph.js
test_data/makedata_suites/960_cursor.js

We need to make looping work again. As anything untested, it was broken.
Some tests need to move functions out to the DB-loop.

QA-460: fix loops

---

test_data/makedata_suites/101_collections.js

Merge this once the test has been fixed.

BTS-1508: re-enable test

---

test_data/makedata_suites/402_views.js
test_data/stress/views.js
test_data/tests/js/common/test-data/apps/itzpapalotl/itzpapalotl.js

fix eslint warnings

---

test_data/makedata_suites/960_cursor.js

we may not have 'moredata' on the initial query. then we don't have a cursor.

if we don't have more data, no cursor was created for later query

---

test_data/makedata_suites/015_cluster_wait.js
test_data/makedata_suites/101_collections.js
test_data/makedata_suites/404_views.js

Fix 404 test for 015 test

---

test_data/makedata_suites/015_cluster_wait.js
test_data/makedata_suites/100_collections.js
test_data/makedata_suites/101_collections.js
test_data/makedata_suites/400_views.js
test_data/makedata_suites/401_views.js
test_data/makedata_suites/402_views.js

Initial commit

---

test_data/makedata_suites/005_check_system_collection.js
test_data/makedata_suites/006_check_system_collection.js

turn off test for system collection in 3.12+

turn off test for system collection in 3.12+

---

test_data/makedata_suites/607_analyzers.js
test_data/makedata_suites/608_analyzers.js
test_data/makedata_suites/609_analyzers.js
test_data/makedata_suites/610_analyzers.js
test_data/makedata_suites/612_analyzers .js
test_data/makedata_suites/612_analyzers.js
test_data/makedata_suites/_600_analyzer_base.js

This PR add tests for following new features:
- [QA-500](https://arangodb.atlassian.net/browse/QA-500)
- [QA-499](https://arangodb.atlassian.net/browse/QA-499)
Also it fixes following critical bug: https://arangodb.atlassian.net/browse/QA-518
Right now we can consider that there is no analyzer tests in RTA at all
[QA-500]: https://arangodb.atlassian.net/browse/QA-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QA-499]: https://arangodb.atlassian.net/browse/QA-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added support for new analyzers

---

test_data/makedata_suites/608_analyzers.js
test_data/makedata_suites/609_analyzers.js
test_data/makedata_suites/_600_analyzer_base.js

Fix sporadically failing tests from https://arangodb.atlassian.net/browse/BTS-1809.

fix BTS-1809

---

test_data/common.js
test_data/makedata.js
test_data/makedata_suites/006_check_system_collection.js
test_data/makedata_suites/010_disabled_uuid_check.js
test_data/makedata_suites/050_database.js
test_data/makedata_suites/051_database_extended_names.js
test_data/makedata_suites/070_foxx.js
test_data/makedata_suites/071_foxx_utf-8.js
test_data/makedata_suites/100_collections.js
test_data/makedata_suites/105_zkd.js
test_data/makedata_suites/106_mdi.js
test_data/makedata_suites/570_enterprise_graph.js
test_data/makedata_suites/900_oneshard.js

We should now create the test data in the collections that we have calculated.

rework rta-makedata to write tests in a chosen database

---

test_data/checkdata.js
test_data/cleardata.js
test_data/common.js
test_data/makedata.js
test_data/makedata_suites/050_database.js
test_data/makedata_suites/051_database_extended_names.js
test_data/makedata_suites/402_views.js
test_data/makedata_suites/610_analyzers.js
test_data/makedata_suites/_600_analyzer_base.js

work on different db support

---

test_data/makedata_suites/010_disabled_uuid_check.js
test_data/makedata_suites/570_enterprise_graph.js

re-enable 570 test

---

test_data/makedata_suites/800_icu.js

This PR introduces a new test to validate the sorting order of Unicode characters following an upgrade to the ICU library in version 3.12. This change affects the comparison results and sorting order in ArangoDB, specifically in indexes.
The main objective of this test is to identify and document any changes in sorting behavior resulting from the ICU library upgrade. The test script 800_icu.js has been created to automate the validation process by:
Creating a collection and inserting specific Unicode character data.
Ensuring the collection has a persistent index.
Validating the sort order of the data using AQL queries.
Final Output:
Based on the thorough testing conducted, the following observations were made:
AQL Sorting Comparison:
Version 3.11.9 and version 3.12.0-2 showed similar …

Adding ICU sorting order test

---

test_data/makedata_suites/802_vpack_sorting.js

This PR adds a test for validating VPack numerical sorting in ArangoDB, specifically addressing sorting behavior for large numeric values across different versions.
Large numeric values were previously cast to doubles for comparison, leading to incorrect sorting and potential data corruption in RocksDB. The issue is fixed in versions 3.12.2 and 3.11.11, introducing a new comparator that requires migration for proper sorting.
Insert Test Data: Add documents with large numeric values to test collections.
Initial Sorting Check:
We now compare against both 3.11.11 and 3.12.2.
For versions older than 3.11.11: Use the incorrect sorting order (z, x, y).
For versions between 3.11.11 and 3.12.2: Still use the incorrect sorting order (z, x, y).
For versions 3.12.2 and newer: Use the correct sorting …

Numerical VPack Sorting test

---

test_data/makedata_suites/802_vpack_sorting.js

fix test: override arangosh number to string convertion to accurately compare numbers of various types(int and double)

---

test_data/makedata_suites/107_vector.js

some things only happen once more than one index is defined.

create another optional index
